Updated gpg and ssh keys to be more consistent with latest version.  Changed read commands to be more consistent.  Fixes to password database.

diff --git a/bashrc_functions_crypt b/bashrc_functions_crypt
--- a/bashrc_functions_crypt
+++ b/bashrc_functions_crypt
@@ -5,7 +5,7 @@
 # Author: Andrew Kroshko
 # Maintainer: Andrew Kroshko <akroshko.public+devel@gmail.com>
 # Created: Tue May 25, 2016
-# Version: 20190624
+# Version: 20190903
 # URL: https://github.com/akroshko/crypt-profiles
 #
 # This program is free software: you can redistribute it and/or modify
@@ -235,7 +235,7 @@ crypt-profile-switch () {
         return 1
     fi
     while read -r -t 0;do read -r; done
-    read -n 1 -p 'Is it OK to delete ~/.ssh/config (y/n)? ' YN
+    read -n 1 -s -r -p 'Is it OK to delete ~/.ssh/config (y/n)? ' YN
     echo ""
     if [[ "$YN" != "y" ]]; then
         yell 'Must be able to replace ~/.ssh/config!'
@@ -312,7 +312,7 @@ crypt-profile-printable () {
         for NAME in ${NAMES[@]}; do
             # echo "here"
             # echo "$NAME"
-            # echo $(gpg --list-keys --fingerprint --keyid-format 0xlong --no-default-keyring --keyring "$KEYSLOCATION/pubring.gpg" "$NAME")
+            # gpg --list-keys --fingerprint --keyid-format 0xlong --no-default-keyring --keyring "$KEYSLOCATION/pubring.gpg" "$NAME"
             # echo "there"
             local STRIPNAME=$(sed -e 's/^ *//g' -e 's/ *$//g' <<< "$NAME")
             local KEYIDS=()
@@ -366,11 +366,8 @@ killall-agents () {
     # XXXX: not completely desirable, but kill gnome keychain because it often interferes
     pkill -9 -f gnome-keyring-daemon
     # this is hopefully enough to purge it
-    [[ -e "$HOME/.gnupg/gpg-agent-info-$HOSTNAME" ]] && rm "$HOME/.gnupg/gpg-agent-info-$HOSTNAME"
-    # TODO: not sure if I ever need this?
-    [[ -e "$HOME/.gpg-agent-info" ]] && rm "$HOME/.gpg-agent-info"
     # TODO: delete only things I own?
-    find /tmp -iname "gpg-*" &>/dev/null && rm /tmp/gpg-*
+    # find /tmp -iname "gpg-*" &>/dev/null && rm /tmp/gpg-*
     [[ -e "$HOME/.keychain" ]] && find "$HOME/.keychain" -type f -delete
 }
 
@@ -591,10 +588,10 @@ decrypt-flatten () {
 ################################################################################
 # containers
 
-container-mount () {
+mount-container () {
     # mount an encrypted luks container on an appropiate mount point
     #
-    local USAGE="Usage: container-mount <<luks container path>> <<mount point>>
+    local USAGE="Usage: mount-container <<luks container path>> <<mount point>>
 
   <<luks container path>> the path to the luks container, the filename
     of the container is the same name used for the mapping in /dev/mapper
@@ -604,6 +601,7 @@ container-mount () {
         echo "$USAGE"
         return 1
     fi
+    # sudo true || { echo "Failed to sudo!"; return 1; }
     local THEBASENAME=$(basename -- "$1")
     if [[ ! -e "/dev/mapper/$THEBASENAME" ]]; then
         msg "Opening $THEBASENAME!"
@@ -614,12 +612,17 @@ container-mount () {
     fi
     # TODO: add more error checking?
     if [[ $? != 4 ]]; then
-        sudo mkdir -p "$2"
+        local MNTBASENAME=$(basename -- "$2")
+        echo "Creating directory: /run/user/$(id -u)/$MNTBASENAME"
+        mkdir -p /run/user/$(id -u)/"$MNTBASENAME"
+        echo "Creating symlink: /run/user/$(id -u)/$MNTBASENAME --> $2"
+        ln -s /run/user/$(id -u)/"$MNTBASENAME" "$2"
         # TODO: do better than this
-        if ! mountpoint -q "$2"; then
-            sudo mount "/dev/mapper/$THEBASENAME" "$2"
-            # TODO: should this be default
-            sudo chown -R "$USER:$USER" "$2"
+        if ! mountpoint -q /run/user/$(id -u)/"$MNTBASENAME"; then
+            sudo mount "/dev/mapper/$THEBASENAME" /run/user/$(id -u)/"$MNTBASENAME"
+            # fuse2fs "/dev/mapper/$THEBASENAME" "$2"
+            # TODO: severe, do not do this
+            # sudo chown -R "$USER:$USER" "$2"
         else
             warn "Mount point $2 already mounted!"
         fi
@@ -627,16 +630,15 @@ container-mount () {
         yell "Cannot find specified container"
     fi
 }
-alias mount-container='container-mount'
 
-container-umount () {
+umount-container () {
     # unmount an encrypted luks container by using exactly the same
-    # arguments as container-mount
+    # arguments as mount-container
     #
     # $1=the path to the luks container, the filename of the container
     #    is the same name used for the mapping in /dev/mapper
     # $2=mount point, deleted after unmounting
-    local USAGE="Usage: container-umount <<luks container path or mount point>>
+    local USAGE="Usage: umount-container <<luks container path or mount point>>
 
   <<luks container path or mount point>> the path to the luks
     container, the filename of the container is the same name used for
@@ -665,14 +667,16 @@ container-umount () {
             return 1
         fi
     fi
+    # sudo true || { echo "Failed to sudo!"; return 1; }
     msg "Unmounting $MOUNTPOINT!"
     sudo umount "$MOUNTPOINT"
+    # fusermount -u "$MOUNTPOINT"
     # TODO: get rid of directory anyways?
     rmdir "$MOUNTPOINT"
+    [[ -h "$1" ]] && rm "$1"
     msg "Closing $MAPPER!"
     sudo cryptsetup luksClose "$MAPPER"
 }
-alias umount-container='container-umount'
 
 open-vg () {
     # open a LVM volume group from an encrypted luks container
@@ -869,7 +873,7 @@ export-firefox-bookmarks () {
     sqlite3 ~/.mozilla/firefox/*.[dD]efault/places.sqlite "SELECT strftime('%d.%m.%Y %H:%M:%S', dateAdded/1000000, 'unixepoch', 'localtime'),url FROM moz_places, moz_bookmarks WHERE moz_places.id = moz_bookmarks.fk ORDER BY dateAdded;"
 }
 
-master-privacy-brief () {
+privacy-brief () {
     # XXXX: suppress automatic privacy clearing if needed
     if [[ -e "$HOME/inhibit-privacy" ]]; then
         yell "Privacy cleanup suppressed!!!"
@@ -879,25 +883,26 @@ master-privacy-brief () {
         # TODO: are things running that I don't want to clear privacy for
         # TODO: add things like vlc to test, or check if anything is currently using places to be shred
         if ! ps -ef | grep --color=never '[f]irefox\|[i]ceweasel\|[p]alemoon\|[w]aterfox' >/dev/null; then
-            master-privacy --batch
+            privacy-full --batch
             echo "$(date-time-stamp) Success" >> "$HOME/.myprivacy.log"
         else
-            warn "Programs running! Will do master-privacy-brief later!"
+            warn "Programs running! Will do privacy-brief later!"
             echo "$(date-time-stamp) Delayed" >> "$HOME/.myprivacy.log"
         fi
     fi
 }
 
-# master-privacy-all () {
+# privacy-all () {
 #     # XXXX: requires crypt-profiles to be in path
-#     sudo env "PATH=$PATH" master-privacy-all.sh "$USER"
+#     sudo env "PATH=$PATH" privacy-all.sh "$USER"
 # }
 
-master-privacy-trash () {
+privacy-trash () {
     h2 "Clearing trash"
+    # TODO: why am I checking this like this?
     if [[ -d "$HOME/tmp/trash/" ]] && find "$HOME/tmp/trash/" -mindepth 1 -print -quit 2>/dev/null | grep --color=never -q .; then
         msg  "Contents of ~/tmp/trash:"
-        ls -A "$HOME"/tmp/trash/*
+        \ls -A "$HOME"/tmp/trash/*
         while read -r -t 0;do read -r; done
         # TODO: add a countdown here
         if ask_yn "Do you want to delete ~/tmp/trash?";then
@@ -906,20 +911,20 @@ master-privacy-trash () {
     else
         warn "Nothing in ~/tmp/trash"
     fi
-    if [[ -d "$HOME/tmp/screenshots/" ]] && find "$HOME/tmp/screenshots/" -mindepth 1 -print -quit 2>/dev/null | grep --color=never -q .; then
-        msg  "Contents of ~/tmp/screenshots:"
-        ls -A "$HOME"/tmp/screenshots/*
+    if [[ -d "$HOME/tmp/screenshots-collect/" ]] && find "$HOME/tmp/screenshots-collect/" -mindepth 1 -print -quit 2>/dev/null | grep --color=never -q .; then
+        msg  "Contents of ~/tmp/screenshots-collect:"
+        \ls -A "$HOME"/tmp/screenshots-collect/*
         while read -r -t 0;do read -r; done
         # TODO: add a countdown here
-        if ask_yn "Do you want to delete ~/tmp/screenshots?";then
-            kill-directory-contents "$HOME/tmp/screenshots"
+        if ask_yn "Do you want to delete ~/tmp/screenshots-collect?";then
+            kill-directory-contents "$HOME/tmp/screenshots-collect"
         fi
     else
-        warn "Nothing in ~/tmp/screenshots"
+        warn "Nothing in ~/tmp/screenshots-collect"
     fi
     if [[ -d "$HOME/.local/share/Trash/files/" ]] && find "$HOME/.local/share/Trash/files/" -mindepth 1 -print -quit 2>/dev/null | grep --color=never -q .; then
         msg "Contents of ~/.local/share/Trash/files/:"
-        ls -A "$HOME/.local/share/Trash/files/"
+        \ls -A "$HOME/.local/share/Trash/files/"
         # TODO: check if empty?
         if ask_yn "Do you want to delete ~/.local/share/Trash/?"; then
             kill-recursive "$HOME/.local/share/Trash/"
@@ -928,14 +933,14 @@ master-privacy-trash () {
         warn "Nothing in $HOME/.local/share/Trash/files/"
     fi
     # always shred tmp-shred if called automatically
-    master-privacy-tmp-shred "$1"
+    privacy-tmp-shred "$1"
 }
 
-master-privacy-tmp-shred () {
+privacy-tmp-shred () {
     # TODO: make interactive
     if [[ -d "$HOME/tmp/tmp-shred/" ]] && find "$HOME/tmp/tmp-shred/" -mindepth 1 -print -quit 2>/dev/null | grep --color=never -q .; then
         msg "Contents of ~/tmp/tmp-shred/:"
-        ls -A "$HOME/tmp/tmp-shred/"
+        \ls -A "$HOME/tmp/tmp-shred/"
         # TODO: check if empty?
         if [[ -n "$1" ]] || ask_yn "Do you want to delete ~/tmp/tmp-shred/?"; then
             kill-recursive "$HOME/tmp/tmp-shred/"
@@ -952,23 +957,28 @@ master-privacy-tmp-shred () {
     fi
 }
 
-master-privacy-conkeror () {
+privacy-conkeror () {
     h2 "Conkeror"
     # XXXX: I now use a password manager and just clear everything
     if ! check-mozilla-running; then
         if [[ -n "$CONKERORTEMPLATEPATH" && -d "$CONKERORTEMPLATEPATH" ]]; then
-            THEDEFAULTDIR=$(find "$HOME/.conkeror.mozdev.org/conkeror/" -mindepth 1 -maxdepth 1 -type d -iname "*.default")
-            if [[ $(wc -l <<< "$THEDEFAULTDIR") == "1" && -d "$THEDEFAULTDIR" ]]; then
-                SHREDDIR="$HOME/tmp/tmp-shred/$(date-time-stamp)-conkeror-profile"
+            for PROFILEDIR in $HOME/.conkeror.mozdev.org/conkeror/*; do
+                [[ -d "$PROFILEDIR" ]] || continue
+                echo "$PROFILEDIR"
+                local PROFILEBASENAME=$(basename -- "$PROFILEDIR")
+                # PROFILEDIR=$(find "$HOME/.conkeror.mozdev.org/conkeror/" -mindepth 1 -maxdepth 1 -type d -iname "*.default")
+                # if [[ $(wc -l <<< "$PROFILEDIR") == "1" && -d "$PROFILEDIR" ]]; then
+                SHREDDIR="$HOME/tmp/tmp-shred/$(date-time-stamp)-conkeror-profile-$PROFILEBASENAME"
                 need_new_directory "$SHREDDIR"
-                mv "$THEDEFAULTDIR" "$SHREDDIR"
-                echo "Trashed old profile at $THEDEFAULTDIR if it existed!"
-                mkdir -p "$THEDEFAULTDIR"
-                cp -r "$CONKERORTEMPLATEPATH"/* "$THEDEFAULTDIR"
-                echo "Copied a new profile as $THEDEFAULTDIR!"
-            else
-                echo "Old conkeror profile not found so nothing trashed!"
-            fi
+                mv "$PROFILEDIR" "$SHREDDIR"
+                echo "Trashed old profile at $PROFILEDIR if it existed!"
+                mkdir -p "$PROFILEDIR"
+                cp -r "$CONKERORTEMPLATEPATH"/* "$PROFILEDIR"
+                echo "Copied a new profile as $PROFILEDIR!"
+                # else
+                #     echo "Old conkeror profile not found so nothing trashed!"
+                # fi
+            done
         elif [[ -d "$HOME/.conkeror.mozdev.org/" ]]; then
             msg "Clearing firefox-based browsers OK!"
             # XXXX: preserve as much as possible, like adblocker
@@ -1002,7 +1012,7 @@ master-privacy-conkeror () {
     fi
 }
 
-master-privacy-firefox () {
+privacy-firefox () {
     h2 "Firefox"
     if ! check-mozilla-running; then
         local FIREFOXPATH_DEFAULT=$(find "$HOME/.mozilla/firefox" -mindepth 1 -maxdepth 1 -type d -iname "*.default")
@@ -1034,7 +1044,7 @@ master-privacy-firefox () {
     # fi
 }
 
-master-privacy-chromium () {
+privacy-chromium () {
     h2 "Chromium"
     # XXXX: I only use chromium as a secondary browser, shredding most things, but keeping adblock?
     if ! check-chromium; then
@@ -1050,7 +1060,7 @@ master-privacy-chromium () {
     # chromium.form_history
 }
 
-master-privacy () {
+privacy () {
     time {
         # TODO: things that ask first...
         # take out any leftover randomfiles used for filling hard drive with junk
@@ -1060,19 +1070,19 @@ master-privacy () {
         # [[ -e "$HOME/randomfile.bin" ]] && sudo rm "$HOME/randomfile.bin"
         # TODO: reset so gnome does not give errors
         h1 "Clearing browser information"
-        master-privacy-chromium
-        master-privacy-firefox
-        master-privacy-conkeror
+        privacy-chromium
+        privacy-firefox
+        privacy-conkeror
         # TODO: any argument will do, not just --batch
         if [[ -z "$1" ]]; then
             h1 "Delete things that need user input"
             # while read -r -t 0;do read -r; done
             # # TODO: check if an sqllite exists before asking
-            # read -n 1 -p "Do you want to delete all Firefox places.sqlite? (y/n) " ynfirefox
+            # read -n 1 -s -r -p "Do you want to delete all Firefox places.sqlite? (y/n) " ynfirefox
             # echo ""
             # this enables always shredding tmp-shred automatically
             if [[ -n "$1" ]] || ask_yn "Do you want to delete ~/tmp/tmp-shred/?"; then
-                master-privacy-trash 1
+                privacy-trash 1
                 local DELETEDTMPSHRED=1
             else
                 local DELETEDTMPSHRED=
@@ -1107,10 +1117,10 @@ master-privacy () {
         else
             # clear $HOME/tmp/tmp-shred automatically, it is a good dumping ground for private files
             if [[ -n "$DELETEDTMPSHRED" ]]; then
-                master-privacy-tmp-shred 1
+                privacy-tmp-shred 1
             fi
         fi
-        # master-privacy-palemoon
+        # privacy-palemoon
         h2 "Flash"
         # TODO: replace with something if flash is ever installed
         kill-directory-contents "$HOME/.abobe/Flash_Player"
@@ -1194,7 +1204,7 @@ master-privacy () {
         # clear $HOME/tmp/tmp-shred automatically, it is a good dumping ground for private files
         # this is done again at the end just in case it is used
         if [[ -n "$DELETEDTMPSHRED" ]]; then
-            master-privacy-tmp-shred 1
+            privacy-tmp-shred 1
         fi
         h2 "Re-caching programs such as Sage and Python"
         # rerun/recomple python and sage if they exist, to restore cached stuff
@@ -1220,11 +1230,11 @@ master-privacy () {
     }
 }
 
-master-privacy-kill-freespace () {
+privacy-kill-freespace () {
     sudo true || { echo "Failed to sudo!"; return 1; }
     local CURRENTUSER="$USER"
-    # TODO: is there a better way to do this
-    sudo su root -c "su $CURRENTUSER -c 'source /home/$CURRENTUSER/.bash_library;master-privacy';kill-freespace-random-file /home/$CURRENTUSER"
+    # TODO: is there a better way to do this, especially assuming we are in /root/
+    sudo su root -c "su $CURRENTUSER -c 'source /home/$CURRENTUSER/.bash_library;privacy';source /root/.bashrc;kill-freespace-random-file /home/$CURRENTUSER"
 }
 
 ################################################################################
@@ -1274,9 +1284,9 @@ fix-sshd-config () {
 ssh-crypt-profile-batch-cmd () {
     # ssh into hostname without interaction by using secrets on current host
     # ssh-crypt-profile-batch-cmd <<hostname>> <<crypt-profile name>> <<command>>
-    local PWDFILE=~/.secrets/"$2".txt.gpg
+    local PWDFILE="$HOME/.secrets/$2.txt.gpg"
     if [[ -f "$PWDFILE" ]]; then
-        local TOPSECRET=$(DISPLAY= gpg-batch --no-tty --decrypt --use-agent "$PWDFILE")
+        local TOPSECRET=$(DISPLAY= gpg-batch --no-tty --decrypt "$PWDFILE")
         if [[ $? == 0 ]]; then
             local GPGPWD=$(sed -n '1p' <<< "$TOPSECRET")
             local B64COMMAND=$(base64 <<< "$3")
