Added some helper functions for batch ssh functionality as well as maintence of logical volume groups.

diff --git a/bash_profile_crypt b/bash_profile_crypt
--- a/bash_profile_crypt
+++ b/bash_profile_crypt
@@ -2,16 +2,23 @@
 # TODO: detect whether this is first attempt on this login
 # TODO: possibly make pinentry-select a dot file in ~
 # TODO: should keychain be done after?
-# TODO: this script will sometimes spit out passwords to the terminal on error, fix do this!!!!
 ################################################################################
 ## this section initializes the GPG key
 # start up the agents
 # from https://wiki.archlinux.org/index.php/GnuPG#gpg-agent
 
+# TODO: still some issues with running this in batch mode, but can send password everytime and it's pretty good
+
 # source ~/.bashrc that should source crypt-profile bash functions
 main () {
     local TRYAGAIN=y
     local TOPSECRET=
+    local GNUPGPWD=
+    # get entered password if necessary
+    if [[ -n "$1" ]]
+    then
+        local GNUPGPWD="$1"
+    fi
     # stop this from being run as root, just in case
     h1 "Running $(basename $BASH_SOURCE)"
     if [[ $EUID -ne 0 ]]
@@ -28,7 +35,6 @@ main () {
         fi
         ln -s /bin/false "${HOME}/bin/pinentry-select"
         if [[ -f ${HOME}/.secrets/secrets.txt.gpg ]]; then
-            # TODO: suppress any output to avoid reveaing passwords
             # TODO: maybe incorporate dummy file
             DISPLAY= gpg2 --batch --decrypt ${HOME}/.secrets/secrets.txt.gpg >> /dev/null
         fi
@@ -43,11 +49,15 @@ main () {
         # otherwise there is an issue with pinentry popping up on a remote
         # X11 display when logging in remotely
         # TODO: describe this issue with GnuPG in documentation
-        if [[ -f "${HOME}/bin/pinentry-select" ]]; then
-            rm -f "${HOME}/bin/pinentry-select"
-        fi
-        if [[ -f /usr/bin/pinentry-curses ]]; then
-            ln -s /usr/bin/pinentry-curses "${HOME}/bin/pinentry-select"
+        # keep pinentry disabled when using $1=$GNUPGPWD because shell is generally non-interactive
+        if [[ -z "$GNUPGPWD" ]]
+        then
+            if [[ -f "${HOME}/bin/pinentry-select" ]]; then
+                rm -f "${HOME}/bin/pinentry-select"
+            fi
+            if [[ -f /usr/bin/pinentry-curses ]]; then
+                ln -s /usr/bin/pinentry-curses "${HOME}/bin/pinentry-select"
+            fi
         fi
         # run keychain after we see if we need to kill agents
         if type -P keychain >/dev/null 2>&1; then
@@ -55,6 +65,7 @@ main () {
             source ${HOME}/.keychain/*-sh > /dev/null
         fi
         msg "Keychain done!"
+        # set up normally if no passphrase given
         while [[ -z $TOPSECRET  && "$TRYAGAIN" == "y" ]]; do
             # TODO: check if this is an agent that I started
             if [[ -e "$envfile" ]] && kill -0 "$(grep GPG_AGENT_INFO $envfile | cut -d: -f 2)" 2>/dev/null; then
@@ -67,10 +78,15 @@ main () {
                 eval "$(DISPLAY= gpg-agent --daemon --allow-preset-passphrase --write-env-file $envfile)"
             fi
             if [[ -f ${HOME}/.secrets/secrets.txt.gpg ]]; then
-                TOPSECRET="$(DISPLAY= gpg2 --decrypt --use-agent ${HOME}/.secrets/secrets.txt.gpg)"
-                if [[ $? != 0 ]]; then
-                    # TODO: add option for quit
-                    read -p "Error decrypting such as bad password.  Try again (y/n/q)? " TRYAGAIN
+                if [[ -n "$GNUPGPWD" ]]
+                then
+                    TOPSECRET="$(DISPLAY= gpg2 --batch --passphrase-fd 0 --decrypt --use-agent ${HOME}/.secrets/secrets.txt.gpg <<< "$GNUPGPWD")"
+                else
+                    TOPSECRET="$(DISPLAY= gpg2 --decrypt --use-agent ${HOME}/.secrets/secrets.txt.gpg)"
+                    if [[ $? != 0 ]]; then
+                        # TODO: add option for quit
+                        read -p "Error decrypting such as bad password.  Try again (y/n/q)? " TRYAGAIN
+                    fi
                 fi
             else
                 # file not present, break by killing appropriate functions
@@ -86,12 +102,17 @@ main () {
     if [[ ! -z $TOPSECRET ]]
     then
         # add identity to gpg-agent
-        GNUPGPWD=`sed -n '1p' <<< "$TOPSECRET"`
+        if [[ -z $GNUPGPWD ]]
+        then
+            local GNUPGPWD=`sed -n '1p' <<< "$TOPSECRET"`
+        fi
         # need to do with fingerprints for both main and subkeys!!!!
         # TODO: possibly need to test for gpg-preset-passphrase working properly
         #       will clearing the agent deal with sleep and hibernation issues?
         for PRESETKEY in ${PRESETGPGKEYS}; do
-            /usr/lib/gnupg2/gpg-preset-passphrase --verbose --passphrase "$GNUPGPWD" --preset "$PRESETKEY"
+            # TODO: run this command if passphrase provided
+            # /usr/lib/gnupg2/gpg-preset-passphrase --verbose --passphrase "$GNUPGPWD" --preset "$PRESETKEY"
+            /usr/lib/gnupg2/gpg-preset-passphrase --verbose --preset "$PRESETKEY" <<< "$GNUPGPWD"
         done
         if [[ -f "${HOME}/.gnupg/gpg-agent-info-$(hostname)" ]]; then
             source "${HOME}/.gnupg/gpg-agent-info-$(hostname)"
@@ -100,21 +121,24 @@ main () {
         ################################################################################
         ## initialize ssh keys only if agent is live
         # read in all id_*.txt.gpg
+        # TODO: add appropriate errors here
         for PWDFILE in ${HOME}/.secrets/id_*.txt.gpg; do
             if [[ -f "${PWDFILE}" ]]; then
                 KEYFILE=$(basename ${PWDFILE%.txt.gpg})
                 h2 "key for ${KEYFILE}"
-                # TODO: suppressing text to make things quieter?
-                # TODO: do not use passphrase here?
-                # TODO: put in function so information does not leak
-                TOPSECRET="$(DISPLAY= gpg2 --quiet --decrypt --use-agent $PWDFILE)"
-                KEYPWD=$(sed -n '1p' <<< "$TOPSECRET")
+                TOPSECRET="$(DISPLAY= gpg2 --quiet --batch --no-tty --decrypt --use-agent $PWDFILE)"
+                if [[ $? == 0 ]]; then
+                    KEYPWD=$(sed -n '1p' <<< "$TOPSECRET")
 expect << EOF
   spawn ssh-add -t 36000 ${HOME}/.ssh/${KEYFILE}
   expect "Enter passphrase"
   send "$KEYPWD\r"
   expect eof
 EOF
+                    msg "Decrypt successful for ${PWDFILE}!"
+                else
+                    warn "Decrypt failed for ${PWDFILE}!"
+                fi
             fi
         done
     else
@@ -129,4 +153,4 @@ EOF
     fi
     h1-end "Finishing $(basename $BASH_SOURCE)"
 }
-main
+main "$1"
diff --git a/bashrc_functions_crypt b/bashrc_functions_crypt
--- a/bashrc_functions_crypt
+++ b/bashrc_functions_crypt
@@ -586,6 +586,32 @@ open-vg () {
     fi
 }
 
+open-vg-maintenance () {
+    # open a LVM volume group from an encrypted luks container
+    # TODO: combine code?
+    local USAGE="Usage: open-vg-maintenance <<luks container path>> <<volume group>>
+
+  <<luks container path>> the path to the luks container, the filename of the container
+    is the same name used for the mapping in /dev/mapper
+
+  <<volume group>> the name of the volume group"
+    if [[ -z "$1" || -z "$2" ]]; then
+        echo "$USAGE"
+        return 1
+    fi
+    if [[ -e "$1" ]]; then
+        if [[ ! -e /dev/mapper/$(basename "$1") ]]; then
+            msg "Opening $(basename "$1")!"
+            sudo cryptsetup luksOpen "$1" $(basename "$1")
+        else
+            warn "Device /dev/mapper/$(basename "$1") already mapped!"
+        fi
+        # TODO: warn if already mapped
+    else
+        warn "Image $1 not found!"
+    fi
+}
+
 close-vg () {
     # close a LVM volume group from an encrypted luks container
     # uses the same set of arguments as open-vg
@@ -812,4 +838,21 @@ fix-sshd-config () {
     # eliminate double lines
     sudo sed -e '/^$/N;/^\n$/D' -i /etc/ssh/sshd_config
     sudo service ssh restart
+}
+
+ssh-crypt-profile-batch-cmd () {
+    # ssh into hostname without interaction by using secrets on current host
+    # ssh-crypt-profile-batch-cmd <<hostname>> <<crypt-profile name>> <<command>>
+    PWDFILE=~/.secrets/"$2".txt.gpg
+    if [[ -f "$PWDFILE" ]]; then
+        TOPSECRET=$(DISPLAY= gpg2 --quiet --batch --no-tty --decrypt --use-agent "$PWDFILE")
+        if [[ $? == 0 ]]; then
+            GPGPWD=$(sed -n '1p' <<< "$TOPSECRET")
+            B64COMMAND="$(echo "$3" | base64)"
+            ssh-batch -t $1 "source ~/.bash_profile $GPGPWD;source ~/.bash_libenv;bash -c \"$(echo ${B64COMMAND} | base64 -d)\""
+        else
+            echo "Error decrypting!!!"
+        fi
+
+    fi
 }
