Better error reporting.

diff --git a/bashrc_functions_crypt b/bashrc_functions_crypt
--- a/bashrc_functions_crypt
+++ b/bashrc_functions_crypt
@@ -1213,7 +1213,7 @@ ssh-crypt-profile-batch-cmd () {
 }
 
 crypt-luks-headers-dump () {
-    sudo true || return 1
+    sudo true || { echo "Failed to sudo!"; return 1; }
     (IFS=$'\n'
      for Z in $(lsblk -l -o name | tail -n +2); do
          if [[ -e /dev/"$Z" ]]; then
diff --git a/bashrc_functions_crypt_external b/bashrc_functions_crypt_external
--- a/bashrc_functions_crypt_external
+++ b/bashrc_functions_crypt_external
@@ -64,7 +64,7 @@ kill-freespace-random-file () {
        local BUFSIZE=2048M
     fi
     echo "Using buffer size $BUFSIZE!"
-    sudo true || return 1
+    sudo true || { echo "Failed to sudo!"; return 1; }
     sudo -i su root <<EOF
 time openssl enc -aes-256-ctr -pass pass:"$(dd if=/dev/urandom bs=128 count=1 2>/dev/null | base64)" -nosalt < /dev/zero | mbuffer -m "$BUFSIZE" -s 64k -A /bin/false -f -o "$ROOTPATH"/randomfile.bin
 sync
@@ -399,7 +399,7 @@ crypt-password-database-retrieve-third () {
 container-create-encrypted () {
     # create an encrypted container formatted to ext4
     # TODO: error checking!!!
-    sudo true || return 1
+    sudo true || { echo "Failed to sudo!"; return 1; }
     local USAGE="Usage: container-create-encrypted <<size>> <<container filename>>"
     if [[ -z "$3" ]];then
         echo "$USAGE"
